import { OnInit, OnDestroy, TemplateRef } from '@angular/core';
import { ModalDirective } from 'ngx-bootstrap/modal';
import { AlertService, AppTranslationService, LocalStoreManager } from '@polpware/ngx-appkit-services-alpha';
import { AuthService } from '@polpware/ngx-oauth2';
import * as i0 from "@angular/core";
export declare class TodoDemoComponent implements OnInit, OnDestroy {
    private alertService;
    private translationService;
    private localStorage;
    private authService;
    static readonly DBKeyTodoDemo = "todo-demo.todo_list";
    rows: any[];
    rowsCache: any[];
    columns: any[];
    editing: {};
    taskEdit: any;
    isDataLoaded: boolean;
    loadingIndicator: boolean;
    formResetToggle: boolean;
    _currentUserId: string;
    _hideCompletedTasks: boolean;
    get currentUserId(): string;
    set hideCompletedTasks(value: boolean);
    get hideCompletedTasks(): boolean;
    verticalScrollbar: boolean;
    statusHeaderTemplate: TemplateRef<any>;
    statusTemplate: TemplateRef<any>;
    nameTemplate: TemplateRef<any>;
    descriptionTemplate: TemplateRef<any>;
    actionsTemplate: TemplateRef<any>;
    editorModal: ModalDirective;
    constructor(alertService: AlertService, translationService: AppTranslationService, localStorage: LocalStoreManager, authService: AuthService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    fetch(cb: any): void;
    refreshDataIndexes(data: any): void;
    onSearchChanged(value: string): void;
    showErrorAlert(caption: string, message: string): void;
    addTask(): void;
    save(): void;
    updateValue(event: any, cell: any, cellValue: any, row: any): void;
    delete(row: any): void;
    deleteHelper(row: any): void;
    getFromDisk(): unknown;
    saveToDisk(): void;
    static ɵfac: i0.ɵɵFactoryDef<TodoDemoComponent, never>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<TodoDemoComponent, "todo-demo", never, { "verticalScrollbar": "verticalScrollbar"; }, {}, never, never>;
}
